ELM-SRCS=$(shell ls *.elm)

deploy: out.html
	set -e
	git clone -b gh-pages https://${GH_TOKEN}@github.com/dreuter/elm-duotris gh-pages

	cp out.html gh-pages/try/index.html

	export COMMIT_HASH=$(shell git rev-parse HEAD)
	echo "$(shell git rev-parse HEAD)" > gh-pages/try/version

	cd gh-pages; git config user.email "daniel.robin.reuter@googlemail.com"
	cd gh-pages; git config user.name "Daniel Reuter (autocommit via travis)"
	cd gh-pages; git add -A .
	cd gh-pages; git commit -a -m "Autogenerated try page from commit $(shell cd .. ; git rev-parse HEAD). Travis build number #$(TRAVIS_BUILD_NUMBER)"
	cd gh-pages; git push --quiet origin gh-pages  > /dev/null 2>&1

out.html: installElm ${ELM-SRCS}
	./Elm-Platform/0.14/bin/elm-make duotris.elm --output out.html --yes

installElm:
	curl -O https://raw.githubusercontent.com/elm-lang/elm-platform/master/installers/BuildFromSource.hs
	runhaskell BuildFromSource.hs 0.14
	touch installElm
